name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t dguest390/shiny-dashboard .

    - name: Run the Docker image
      run: docker run -d --rm -p 3838:3838 dguest390/shiny-dashboard

    - name: Ping the running image
      run: curl http://127.0.0.1:3838
