name: Build, run, and ping the container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build container image
      run: docker build -t shiny-dashboard .

    - name: Run the container image and ping it
      run: |
        docker run -p 3838:3838 -d shiny-dashboard 
        sleep 10s  # Give container some time to start
        curl http://172.17.0.2:3838

