on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image and ping
      run: |
        docker build -t dguest390/shiny-dashboard .
        container_id = $(docker run -d -p 3838:3838 dguest390/shiny-dashboard)
        docker container inspect $container_id

