on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t dguest390/shiny-dashboard .
    
    - name: Ping local host
      run: |
          docker run -d --rm -p 3838:3838 dguest390/shiny-dashboard
          curl http://localhost:3838/
