name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  first-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dguest390/shiny-dashboard:$(date +%s)
      
  second-job:
    
    needs: first-job
    runs-on: ubuntu-latest
    
    steps:
    - name: Run the Docker image
      run: docker run -d --rm -p 3838:3838 dguest390/shiny-dashboard 
      
      
    
